on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          ftp-server: ${{ secrets.ftp_host }}
          ftp-username: ${{ secrets.ftp_user }}
          ftp-password: ${{ secrets.ftp_password }}
          local-dir: public/
          exclude: .git*
            - **.git*
            - .git*/**
            -  **/.git*/**
            - node_modules/**
            - node_modules/**/*
